# Generated by Django 2.2.11 on 2020-03-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
    ]
